name: CI
on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: GitLeaks (secrets)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bandit (SAST)
        run: pip install bandit && bandit -r app.py
      - name: Safety (dépendances)
        run: pip install safety && safety check -r requirements.txt

  build-and-sign:
    needs: security-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: eu-west-3
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build
        run: docker build -t ${{ steps.login-ecr.outputs.registry }}/myapp:${{ github.sha }} .
      - name: Trivy (scan image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/myapp:${{ github.sha }}
          severity: CRITICAL,HIGH
          exit-code: 1          # le pipeline échoue si vulnérabilité grave
          ignore-unfixed: true
      - name: SBOM (Syft)
        uses: anchore/sbom-action@v0
        with:
          image: ${{ steps.login-ecr.outputs.registry }}/myapp:${{ github.sha }}
          format: spdx-json
          output-file: sbom.spdx.json
      - name: Push
        run: docker push ${{ steps.login-ecr.outputs.registry }}/myapp:${{ github.sha }}
      - uses: sigstore/cosign-installer@v3
      - name: Sign image (Cosign keyless)
        run: |
          IMAGE="${{ steps.login-ecr.outputs.registry }}/myapp:${{ github.sha }}"
          DIGEST="$(docker inspect --format='{{index .RepoDigests 0}}' "$IMAGE" | cut -d@ -f2)"
          cosign sign --yes "${{ steps.login-ecr.outputs.registry }}/myapp@${DIGEST}"